Require the `changelog:` entry in the PR body to be modified
Currently just keeping `changelog: none` in the PR description, won't
trip up bors. This is a problem, if the reviewer (me) doesn't pay
attention to this, since `CHANGELOG.md` may miss important changes
later.

This change shouldn't be a burden for contributors, but reviewers. Every
reviewer should have permissions to change PR descriptions.

diff --git a/.github/workflows/clippy_bors.yml b/.github/workflows/clippy_bors.yml
--- a/.github/workflows/clippy_bors.yml
+++ b/.github/workflows/clippy_bors.yml
@@ -40,8 +40,9 @@ jobs:
         if [[ -z "$output" ]]; then
           echo "ERROR: PR body must contain 'changelog: ...'"
           exit 1
-        elif [[ "$output" = "none" ]]; then
-          echo "WARNING: changelog is 'none'"
+        elif [[ -n $(echo "$output" | grep -i "^\s*none\.*$") ]]; then
+          echo "ERROR: changelog is 'none', use 'internal' for internal only changes"
+          exit 1
         fi
       env:
         PYTHONIOENCODING: 'utf-8'
